# Generated by Django 4.2.6 on 2023-11-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeding',
            name='meal',
            field=models.CharField(choices=[('B', 'Berry'), ('R', 'Razz Berry'), ('P', 'Pinap Berry')], default='B', max_length=1),
        ),
    ]
