# Generated by Django 4.2.6 on 2023-11-01 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cat',
            new_name='Pokemon',
        ),
    ]
