# Generated by Django 4.2.6 on 2023-11-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_feeding_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeding',
            name='meal',
            field=models.CharField(choices=[('N', 'Nanab Berry'), ('R', 'Razz Berry'), ('P', 'Pinap Berry')], default='N', max_length=1),
        ),
    ]
