# Generated by Django 4.2.6 on 2023-11-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_held_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='held_items',
            field=models.ManyToManyField(to='main_app.held_item'),
        ),
    ]
